export const COURSE_LIST = [
  { value: '0', label: 'ALL' },
  { value: 'ADMN', label: 'Business Administration' },
  { value: 'ANII', label: 'Anishinaabe Studies' },
  { value: 'ANTR', label: 'Anthropology' },
  { value: 'AVIA', label: 'Aviation' },
  { value: 'BIOL', label: 'Biology' },
  { value: 'CESD', label: 'Community Economic & Social Development' },
  { value: 'CHMI', label: 'Chemistry' },
  { value: 'COOP', label: 'Cooperative Education' },
  { value: 'COSC', label: 'Computer Science' },
  { value: 'ECON', label: 'Economics' },
  { value: 'ENGL', label: 'English' },
  { value: 'ENVS', label: 'Environmental Science' },
  { value: 'ESPA', label: 'Spanish' },
  { value: 'FILM', label: 'Film Studies' },
  { value: 'FRAN', label: 'French' },
  { value: 'GEOG', label: 'Geography' },
  { value: 'GEOL', label: 'Geology' },
  { value: 'HIST', label: 'History' },
  { value: 'ITAL', label: 'Italian' },
  { value: 'ITEC', label: 'Information Technology' },
  { value: 'JURI', label: 'Law & Justice' },
  { value: 'MATH', label: 'Mathematics' },
  { value: 'MUSC', label: 'Music' },
  { value: 'OJIB', label: 'Anishinaabemowin' },
  { value: 'PHIL', label: 'Philosophy' },
  { value: 'PHYS', label: 'Physics' },
  { value: 'POLI', label: 'Political Science' },
  { value: 'PSYC', label: 'Psychology' },
  { value: 'SOCI', label: 'Sociology' },
  { value: 'STAT', label: 'Statistics' },
  { value: 'SWRK', label: 'Social Work' },
  { value: 'VISA', label: 'Visual Arts' }
]
